### ISSUE TITLE
다크모드 활성화 이슈

### ISSUE THREAD

**Issue by june-hehe** [hidaehyunlee/HWIBAL#115]
1. 다크모드 버튼 토글시 설정 미반영
2. 앱 재시작시 다크모드 강제 적용

https://github.com/hidaehyunlee/HWIBAL/assets/139306158/ae0744ad-06c8-45fa-b273-e529060eaed9

**Comment by anfgbwl** [comment]
PR #121 에 보완 완료했습니당
