### ISSUE TITLE
[TestFlight - Create] 텍스트뷰 폰트 사이즈 up 제안

### ISSUE THREAD

**Issue by anfgbwl** [hidaehyunlee/HWIBAL#127]
- 텍스트뷰 폰트 사이즈 1~2px 올려도 될 듯
- 현재 텍스트뷰에 적용된 폰트 사이즈를 기준으로 FontGuide 파일에 사이즈 추가해도 됨

| 실기기 캡쳐 | 폰트 비교용 캡쳐(피드백) |
|:--:|:--:|
|<img src="https://github.com/hidaehyunlee/HWIBAL/assets/53863005/f1cf7e94-acf1-42f7-b2fa-5d62f6f1a474">|![image](https://github.com/hidaehyunlee/HWIBAL/assets/53863005/888950fc-dbeb-4646-8ca2-7738b278482b)|

**Comment by doyuny** [comment]
extView.font = FontGuide.size16로 변경
