### ISSUE TITLE
[DetaileView] 감정쓰레기가 없을 시 보여줄 새 VC 필요

### ISSUE THREAD

**Issue by hidaehyunlee** [hidaehyunlee/HWIBAL#28]
유저 감정쓰레기가 0개일 때는 DetailViewController가 아니라 다른 VC를 만들어서
_**현재 작성된 감정쓰레기가 없습니다**_  등의 메세지를 보여주면 좋을 것 같습니다.

**Comment by anfgbwl** [comment]
홈VC에서 감쓰 0개 일때는 디테일로 이동하지 말고 Alert로 감쓰가 없다고 표현하는 방법도 있겠네요~

**Comment by anfgbwl** [comment]
Figma에 추가된 레이아웃 확인하셔서 작업해주세용~
코드는 #75 참조하시면 됩니다~

**Comment by hidaehyunlee** [comment]
PR #81 에서 해결
