### ISSUE TITLE
[Alert] 삭제 Alert 메세지 워딩 수정

### ISSUE THREAD

**Issue by anfgbwl** [hidaehyunlee/HWIBAL#32]
전체 삭제: 정말로 전체 지우시겠습니까?
개별 삭제: 정말로 삭제 하시겠습니까?

워딩이 뭔가 어색한 느낌이 있어서 레퍼런스 찾아보고 수정 제안 드리겠습니다.

**Comment by anfgbwl** [comment]
Alert 확인 타이틀 수정

휘발 -> 확인

**Comment by anfgbwl** [comment]
1. 전체삭제
* 감정쓰레기를 모두 삭제하시겠습니까?
* 감정쓰레기를 모두 삭제하시겠습니까? 이 작업은 실행 취소할 수 없습니다.
* 감정쓰레기를 모두 삭제하시겠어요?
* 삭제된 감정쓰레기는 복구할 수 없습니다. 삭제하시겠습니까?


2. 개별삭제
* 이 감정쓰레기를 삭제하시겠습니까?
* 이 감정쓰레기를 삭제하시겠습니까? 이 작업은 실행 취소할 수 없습니다.
* 정말로 이 감정쓰레기를 삭제하시겠습니까?
* 이 감정쓰레기를 정말 삭제하시겠어요?
* 이 감정쓰레기를 삭제하시겠어요?
* 삭제된 감정쓰레기는 복구할 수 없습니다. 삭제하시겠습니까?

3. 확인 워딩
* 삭제(style: .destructive)

![IMG_9977](https://github.com/hidaehyunlee/HWIBAL/assets/53863005/47fbc923-26b5-4e79-9ade-d9b4e709ee16)
![IMG_9976](https://github.com/hidaehyunlee/HWIBAL/assets/53863005/79cc760f-433e-4da1-b9b1-fee7bcc07700)
![IMG_618F249688E7-1](https://github.com/hidaehyunlee/HWIBAL/assets/53863005/975dcf5a-2d19-44d6-a729-7177d87f3fbb)

**Comment by doyuny** [comment]
10/26일 내로 변경하겠습니당
