### ISSUE TITLE
[DetailPage] 개별 삭제 클릭 시 작동 안함

### ISSUE THREAD

**Issue by anfgbwl** [hidaehyunlee/HWIBAL#33]
개별 삭제 Alert 적용이 안되어 있습니다.

**Comment by anfgbwl** [comment]
이 문제는 아마도 이거같아요!

`EmotionTrashService.shared.deleteEmotionTrash(self.signedInUser, cellId!)`

여기서 signedInUser을 초기 선언하면 안되고 deleteEmotionTrash 함수 실행할 때 바로 SignInService.shared.signedInUser!를 호출해야합니다.

private var signedInUser = SignInService.shared.signedInUser!
이렇게 선언해두고 signedInUser를 쓰게되면, 이전 로그인 유저로 저장될 가능성이 있어요!

**Comment by hidaehyunlee** [comment]
#57  에서 해결했습니다 !
