### ISSUE TITLE
[CreatePage] 작성 취소 Alert 미작동

### ISSUE THREAD

**Issue by anfgbwl** [hidaehyunlee/HWIBAL#35]
작성 취소를 취소할 경우 modal이 닫힘(작성내용이 없을 때)
<image src="https://github.com/hidaehyunlee/HWIBAL/assets/53863005/fc580604-1a84-4fa6-9ed1-052cf7f17032" width="300">

**Comment by doyuny** [comment]
10/26일 내로 변경하겠습니당
