### ISSUE TITLE
[DetailPage] 컨텐츠 짤려서 보이는 문제

### ISSUE THREAD

**Issue by anfgbwl** [hidaehyunlee/HWIBAL#37]
만약 작성자가 엔터를 눌러서 감쓰를 작성했을 때
글자수 제한에 걸리지는 않지만, 디테일페이지에서는 텍스트뷰 높이 제한이 있어서 내용이 짤림(내용도 짤리고, 작성일자도 덮어짐)

이 경우에는 스크롤이 가능하도록 설정하는게 좋을 듯(다른 방법이 있다면 뭐든 OK)

<img src = "https://github.com/hidaehyunlee/HWIBAL/assets/53863005/6098414d-07d4-432d-8d32-dc1e68d06e34" width = 300>

**Comment by hidaehyunlee** [comment]
PR #43 에서 해결했습니다
