### ISSUE TITLE
[DetailPage/ReportPage] 맨 처음으로, 맨 위로 클릭 시 페이지 카운팅 적용 안됨

### ISSUE THREAD

**Issue by anfgbwl** [hidaehyunlee/HWIBAL#39]
좌우 상하 스크롤 시 페이지 카운팅 적용되는데, 맨 처음으로/맨위로 버튼 클릭 시 적용 안됨

![Simulator Screen Recording - iPhone 14 Pro - 2023-10-26 at 15 25 38](https://github.com/hidaehyunlee/HWIBAL/assets/53863005/16127463-ff26-46f8-9db9-5aca3c32787c) ![Simulator Screen Recording - iPhone 14 Pro - 2023-10-26 at 15 25 50](https://github.com/hidaehyunlee/HWIBAL/assets/53863005/f702d3c6-709b-41dc-8319-e93875a8d050)

**Comment by anfgbwl** [comment]
Report Page 이슈 보완 완료 PR #58 참조
(Detail Page 적용 후 Close 예정)

**Comment by hidaehyunlee** [comment]
디페일페이지 부분 PR #60 에서 수정했습니다
