### ISSUE TITLE
[DetailPage] 다크모드 시 배경 색 적용 안됨

### ISSUE THREAD

**Issue by anfgbwl** [hidaehyunlee/HWIBAL#41]
<img src = "https://github.com/hidaehyunlee/HWIBAL/assets/53863005/1b9c4946-1e14-494f-afb3-ce289ab68001" width = 300> <img src = "https://github.com/hidaehyunlee/HWIBAL/assets/53863005/d8bc20ca-a7ad-494a-8e8f-9d149080196a" width=300>

viewDidLoad에 뷰 백그라운드 컬러 지정되어 있음
```
override func viewDidLoad() {
        super.viewDidLoad()

        view.backgroundColor = .white
```

**Comment by hidaehyunlee** [comment]
PR #43 에서 해결했습니다
