### ISSUE TITLE
[CreatePage] 이미지 첨부 시 코어데이터로 넘겨주는 값 없음

### ISSUE THREAD

**Issue by anfgbwl** [hidaehyunlee/HWIBAL#45]
이미지 첨부 안됨

`let text = rootView.textView.text ?? ""
        EmotionTrashService.shared.createEmotionTrash(SignInService.shared.signedInUser!, text)`

이미지 넘겨주는 코드 없음

**Comment by doyuny** [comment]
`   @objc func showWriteAlert() {
        AlertManager.shared.showMessageAlert(on: self, title: "아, 휘발 🔥", message: "오... 그랬군요 🥹 \n당신의 감정을 휘발주기에 맞추어 불태워 드릴게요 🔥") {
            let text = self.rootView.textView.text ?? ""
            // attachedImageView가 nil인지 & imageView의 image 속성이 nil인지 확인 -> nil아닐 경우 저장
            if let imageView = self.attachedImageView, let attachedImage = imageView.image {
                print("attachedImageView 첨부")
                EmotionTrashService.shared.createEmotionTrash(SignInService.shared.signedInUser!, text, attachedImage)
            } else {
                print("attachedImageView nil")
                EmotionTrashService.shared.createEmotionTrash(SignInService.shared.signedInUser!, text)
            }
            EmotionTrashService.shared.printTotalEmotionTrashes(SignInService.shared.signedInUser!)
            NotificationCenter.default.post(name: NSNotification.Name("EmotionTrashUpdate"), object: nil)

            self.dismiss(animated: true, completion: nil)
        }
    }`
    이렇게 바꿨는데 괜찮을까용?

**Comment by doyuny** [comment]
`   @objc func showWriteAlert() {
        AlertManager.shared.showMessageAlert(on: self, title: "아, 휘발 🔥", message: "오... 그랬군요 🥹 \n당신의 감정을 휘발주기에 맞추어 불태워 드릴게요 🔥") {
            let text = self.rootView.textView.text ?? ""
            // attachedImageView가 nil인지 & imageView의 image 속성이 nil인지 확인 -> nil아닐 경우 저장
            if let imageView = self.attachedImageView, let attachedImage = imageView.image {
                print("attachedImageView 첨부")
                EmotionTrashService.shared.createEmotionTrash(SignInService.shared.signedInUser!, text, attachedImage)
            } else {
                print("attachedImageView nil")
                EmotionTrashService.shared.createEmotionTrash(SignInService.shared.signedInUser!, text)
            }
            EmotionTrashService.shared.printTotalEmotionTrashes(SignInService.shared.signedInUser!)
            NotificationCenter.default.post(name: NSNotification.Name("EmotionTrashUpdate"), object: nil)

            self.dismiss(animated: true, completion: nil)
        }
    }`
