### ISSUE TITLE
[CreateView] 이미지 추가 버튼 눌렀을 때 액션시트 워딩 변경

### ISSUE THREAD

**Issue by hidaehyunlee** [hidaehyunlee/HWIBAL#52]
<img width="300" alt="image" src="https://github.com/hidaehyunlee/HWIBAL/assets/37580034/3d69c571-7641-4a7b-9e73-26dfa15245e9">

- 지금 영어로 되어있는데 한글(카메라, 앨범, 취소(빨간색))로 변경하면 조을것 같슴니다.
- choose image source 액션시트 타이틀도 변경해야겠네요 -> 이미지 선택 등 ..

**Comment by doyuny** [comment]
cancle도 취소로 바꿀까요?

**Comment by hidaehyunlee** [comment]
넵 저는 그게 좋을 것 같아요!
