### ISSUE TITLE
[Alert] AlertManager 파일명 변경 요청

### ISSUE THREAD

**Issue by anfgbwl** [hidaehyunlee/HWIBAL#53]
클래스명은 AlertManager인데, 파일명은 AlertViewController여서 혼돈이 예상됩니다.
파일 위치도 Services로 변경하는게 좋을 듯 합니다.

<img width="976" alt="image" src="https://github.com/hidaehyunlee/HWIBAL/assets/53863005/23f677d0-77ac-4f10-b2bb-46671882cb60">

**Comment by doyuny** [comment]
넵!
