### ISSUE TITLE
[MyPage] 공통컴포넌트 Alert 적용 여부 확인 요청

### ISSUE THREAD

**Issue by anfgbwl** [hidaehyunlee/HWIBAL#54]
현재 AlertManager에는 게시물 삭제와 작성완료만 사용할 수 있는 Alert가 구현되어 있습니다.
okAction 타이틀 자체가 "삭제"로 고정되어 있어, 마이페이지에 로그아웃/회원탈퇴에 적용하기에 어려움이 있습니다.

해결 방안은 2가지 입니다.
1. AlertManager에서 타이틀도 입력받을 수 있게 수정
2. MyPage에서 구현되는 모든 Alert는 actionsheet 형태로 별도 작업

[AlertManager - actionsheet 비교]
<img src="https://github.com/hidaehyunlee/HWIBAL/assets/53863005/65c14c6d-3d3d-4ed0-bc93-6596f7509048" width=250> <img src="https://github.com/hidaehyunlee/HWIBAL/assets/53863005/31fdd92d-8f57-4593-b23e-d3ce86a1ec05" width=250> <img src="https://github.com/hidaehyunlee/HWIBAL/assets/53863005/d09d8509-ed82-4f26-a1e2-6f33f815f462" width=250>

**Comment by hidaehyunlee** [comment]
- [Getting the user’s attention with alerts and action sheets](https://developer.apple.com/documentation/uikit/windows_and_screens/getting_the_user_s_attention_with_alerts_and_action_sheets)
- [[iOS] Alert, ActionSheet 톺아보기](https://k-elon.tistory.com/28)

모든 알러트들을 다 통일하면 좋을 것 같은데 위 링크도 참고해보면 결정할 때 도움될 거같아요
저는 갠적으로 디자인은 액션시트가 이쁜데, alert에는 타이틀을 분명하게 넣을 수 있어서 그게 장점같아요 ..

**Comment by anfgbwl** [comment]
로그아웃, 회원탈퇴는 actionSheet로 작업했습니다.
