### ISSUE TITLE
[실기기 테스트 - Create] dateLabel 센터 정렬 안맞음

### ISSUE THREAD

**Issue by anfgbwl** [hidaehyunlee/HWIBAL#77]
* dateLabel snapKit으로 CenterX 맞추면 문제 해결될 듯
<img src="https://github.com/hidaehyunlee/HWIBAL/assets/53863005/7d3f022f-dc98-478d-8161-ae4b14ed4c1f" width=300>

**Comment by doyuny** [comment]
dateLabel snapKit으로 변경하였습니다.
make.centerX.equalToSuperview()도 추가했습니다!
